#version: "3.7"
#services:
#  oracle-server-db:
#    image: gvenzl/oracle-xe
#    environment:
#      ORACLE_PASSWORD: "Admin"
#    ports:
#      - "1521:1521"

version: "3.3"
services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: "starwars"
      MYSQL_ROOT_PASSWORD: "Admin@"
    ports:
      - "3308:3306"